Repository yamaton/condax, pull requests merged in 2022-08, with the labels that each got.

#7 Tidy up logging and errors
  condax/cli.py
  condax/cli/__init__.py
  condax/cli/__main__.py
  condax/cli/ensure_path.py
  condax/cli/export.py
  condax/cli/inject.py
  condax/cli/install.py
  condax/cli/list.py
  condax/cli/remove.py
  condax/cli/repair.py
  condax/cli/update.py
  condax/conda.py
  condax/config.py
  condax/core.py
  condax/exceptions.py
  condax/paths.py
  condax/utils.py
  environment.yml
  setup.py
  tests/test_condax_update.py
  tests/test_config.py
Labels: enhancement

#9 Tidied up cli
  condax/cli/__init__.py
  condax/cli/ensure_path.py
  condax/cli/export.py
  condax/cli/inject.py
  condax/cli/install.py
  condax/cli/list.py
  condax/cli/options.py
  condax/cli/remove.py
  condax/cli/repair.py
  condax/cli/update.py
  condax/utils.py
Labels: refactor

#13 Fix TypeError when --channel is specified in CLI
  condax/cli/options.py
Labels: bug
